### ISSUE TITLE
Specify goals and expectations for feature fetcher

### ISSUE THREAD

**Issue by geneorama** [Chicago/sdp-feature-fetcher#1]
@tomschenkjr I think we should document the goals of the of this project in the repository.  Here are some notes / questions.

 + Where should we store the objectives on github? (e.g. readme, wiki, issues, or should we start a DESCRIPTION file?)
 + Per our discussions, my plan is to develop this into an R package, but I'm going to start with scripts that accomplish basic tasks, with the plan to use the scripts as a basis for both functions and tests.
 + What will the data flow look like; e.g. will the inputs to the feature fetcher be a file or an in-memory query
 + Where should the outcome be stored (I'm assuming in-memory for now)
 + For now I'm planning to mirror the food inspection fields first using the two records from https://github.com/Chicago/sdp-business.json, and I'm planning to make the output appropriate to be an input for the Argonne model https://xgitlab.cels.anl.gov/uda/ml-city/

**Comment by geneorama** [comment]
@tomschenkjr 
My current thinking is that there are three main milestones here:
 1. Generate features based on past inspections
 2. Generate features based on information related to the business (mainly past licenses)
 3. Generate features based on location based data (kde calculations based on point data)

I'm currently working on the third item, since it's actually the cleanest in terms of data. I am not putting things in functions yet or organizing things as a package.  I'm focusing on getting the basics working and importing code examples.

**Comment by geneorama** [comment]
There is also a 4th milestone of wrapping up items 1-3 together.

**Comment by tomschenkjr** [comment]
@geneorama - yes, that is a good outline.

**Comment by geneorama** [comment]
@tomschenkjr An initial version is complete (as of last week).

## First step: Parsing and basic business / inspection features

You pass the JSON file into `parseRecords` and you get a table of inspections and "business features" based on the inspection. The function `parseRecords` calls `parseRecord`, which is the important function. The function `parseRecord` takes the following arguments 

 - `inspectionType` This is the name of the top level list that contains the inspections.  For the first example it's "foodInspections".
 - `targetFieldName` This is the name of the result that you want to pull out.  In this case it's a field called "result" that can be either "PASS" or "FAIL"
 - `targetCriteria` This is code that gets evaluated to create boolean results.  In this example the criteria is `==FAIL`.  This string is appended to the strings contained in the `targetFieldName` and it's evaluated so that (in this case) FAIL will appear as a TRUE and anything else will be FALSE. 
 - `evalDays` This a vector of integers that represent the days at which the target field is evaluated. So in the example `c(90, 365, 365 * 2)` the target is evaluated at 90 days, 1 year, and 2 years. This is translated into "events" in the past N days (meaning in this case any inspection) and "target events" in the past N days (meaning in this case number of inspections that were equal to the string "FAIL")

The way the target criteria is formulated it's possible to pass in other criteria that will evaluate numeric results.  So rather than "==FAIL" you could specify something like ">235" for a numeric result with a target variable named "CFU" for the beach project. 

### Next step: density calculations

In the next step the date / longitude / latitude columns are passed into `getDensity`, which is the density calculator.  You also specify the dataset name, days back, optional filters, KDE density `h`, and whether you want just the density calculation or the density calculation and the supporting event data.

Once you have the z values you join them to the table produced in the first step.

The first and second step could be rolled up into another wrapper. 

### Limitations

- Even this small example uses a lot of memory, and can't run on my 32bit 4GB machine. The problem is that for these two businesses the inspection records still span several years, and to calculate the density figures for sanitation and garbage cart requests (for example) almost the entire data set need to be downloaded into memory, and I run out of space.  The code works on the analytics server of course, which is where I tested it. 
 - There is no test of whether the calculated features span the requested timeframe. For example, if you used "towed vehicles" in your density calculation You would get KDE values for recent inspections, but no warning that old inspections were zero because of a lack of data coverage (since that data set only goes back 90 days). 
 - There is no ability to pull out historical license types because I don't have them available in the data example. 

The output looks like this:
![image](https://cloud.githubusercontent.com/assets/1392068/24622286/0de1f7a8-186a-11e7-9f94-554e7699ecc0.png)

Code to reproduce the above example (I didn't run the second two density functions for the example, but they do work on machines with more memory). 
```R
## Load package functions
sapply(list.files("R", full.names = TRUE), source)

## load sample
recs <- parseRecords(RJSONIO::fromJSON("data/examp_mod.json"))

densCrime <- getDensity(records = recs[ , list(date = actionDate, longitude, latitude)], 
                        datasetname = "crimes_2001_to_present", 
                        filter = "primary_type=ARSON",
                        daysback = 365,
                        h = .01,
                        return_events = FALSE)
densSanitation <- getDensity(records = recs[ , list(date = actionDate, longitude, latitude)], 
                             datasetname = "311_service_requests_sanitation_code_complaints", 
                             daysback = 365,
                             h = .01,
                             return_events = FALSE)
densGarbage <- getDensity(records = recs[ , list(date = actionDate, longitude, latitude)], 
                          datasetname = "311_service_requests_garbage_carts", 
                          daysback = 365,
                          h = .01,
                          return_events = FALSE)

recs[ , densCrime := densCrime[ , z]]
recs[ , densSanitation := densSanitation[ , z]]
recs[ , densGarbage := densGarbage[ , z]]

recs
```

**Comment by geneorama** [comment]
I think this first issue can be closed.
